module.exports = [
  {
    key: '1',
    index: 1,
    name: '传奇系列游戏合集',
    pictureUrl: '',
    isHot: '是',
    time: '2017.5.5',
  },
  {
    key: '2',
    index: 2,
    name: '宫斗穿越及文字剧情游戏合集',
    pictureUrl: '',
    isHot: '是',
    time: '2017.4.5',
  },
  {
    key: '3',
    index: 3,
    name: '精彩消消乐手机小游戏大全',
    pictureUrl: '',
    isHot: '是',
    time: '2017.3.5',
  },
  {
    key: '4',
    index: 4,
    name: '传奇系列游戏合集',
    pictureUrl: '',
    isHot: '是',
    time: '2017.5.5',
  },
  {
    key: '5',
    index: 5,
    name: '宫斗穿越及文字剧情游戏合集',
    pictureUrl: '',
    isHot: '是',
    time: '2017.4.5',
  },
];
